#import <Foundation/Foundation.h>

//! Project version number for Sentry.
FOUNDATION_EXPORT double SentryVersionNumber;

//! Project version string for Sentry.
FOUNDATION_EXPORT const unsigned char SentryVersionString[];

#import "SentryBreadcrumb.h"
#import "SentryBreadcrumbTracker.h"
#import "SentryClient.h"
#import "SentryCrashExceptionApplication.h"
#import "SentryCurrentDate.h"
#import "SentryCurrentDateProvider.h"
#import "SentryDebugMeta.h"
#import "SentryDefaultCurrentDateProvider.h"
#import "SentryDefaultRateLimits.h"
#import "SentryEnvelope.h"
#import "SentryEnvelopeItemType.h"
#import "SentryError.h"
#import "SentryEvent.h"
#import "SentryException.h"
#import "SentryFrame.h"
#import "SentryHttpDateParser.h"
#import "SentryHttpTransport.h"
#import "SentryHub.h"
#import "SentryInstallation.h"
#import "SentryMechanism.h"
#import "SentryNSURLRequest.h"
#import "SentryQueueableRequestManager.h"
#import "SentryRateLimitCategory.h"
#import "SentryRateLimitCategoryMapper.h"
#import "SentryRateLimitParser.h"
#import "SentryRateLimits.h"
#import "SentrySDK.h"
#import "SentryScope.h"
#import "SentrySerializable.h"
#import "SentrySerialization.h"
#import "SentryStacktrace.h"
#import "SentrySwizzle.h"
#import "SentryThread.h"
#import "SentryTransport.h"
#import "SentryTransportFactory.h"
#import "SentryUser.h"
#import "NSData+SentryCompression.h"
#import "NSDate+SentryExtras.h"
#import "NSDictionary+SentrySanitize.h"
#import "NSString+SentryUnsignedLongLongValue.h"
#import "SentryAsynchronousOperation.h"
#import "SentryAutoBreadcrumbTrackingIntegration.h"
#import "SentryAutoSessionTrackingIntegration.h"
#import "SentryConcurrentRateLimitsDictionary.h"
#import "SentryCrashAdapter.h"
#import "SentryCrashBinaryImageProvider.h"
#import "SentryCrashDefaultBinaryImageProvider.h"
#import "SentryCrashDefaultMachineContextWrapper.h"
#import "SentryCrashInstallationReporter.h"
#import "SentryCrashIntegration.h"
#import "SentryCrashIsAppImage.h"
#import "SentryCrashReportConverter.h"
#import "SentryCrashReportSink.h"
#import "SentryCrashStackEntryMapper.h"
#import "SentryDateUtil.h"
#import "SentryDebugMetaBuilder.h"
#import "SentryDsn.h"
#import "SentryEnvelopeRateLimit.h"
#import "SentryFileContents.h"
#import "SentryGlobalEventProcessor.h"
#import "SentryHexAddressFormatter.h"
#import "SentryLog.h"
#import "SentryMeta.h"
#import "SentryRequestOperation.h"
#import "SentryRetryAfterHeaderParser.h"
#import "SentryScope+Private.h"
#import "SentrySdkInfo.h"
#import "SentrySessionTracker.h"
#import "SentryThreadInspector.h"
